import type { WeddingDataConfig, WeddingImagesConfig } from "../types/wedding";

export const weddingImages: WeddingImagesConfig = {
  hero: {
    backgroundDesktop: "/images/hero/hero-background/desktop/hero-background-desktop.jpg",
    backgroundMobile: "/images/hero/hero-background/mobile/hero-background-mobile.jpg",
    backgroundBand: "/images/hero/hero-background/band/hero-background-band.jpg",
    backgroundTiny: "/images/hero/hero-background/thumbnail/hero-background-tiny.jpg",
    floralLeft: "/images/hero/hero-floral-left/hero-floral-left.jpg",
    floralRight: "/images/hero/hero-floral-right/hero-floral-right.jpg",
    waxSeal: "/images/hero/envelope-wax-seal/wax-seal.jpg",
    cardFloral: "/images/hero/invitation-card/card-floral.jpg",
  },
  story: {
    editorial: {
      polaroid01: "/images/story/editorial/polaroid-01/polaroid-01.jpg",
      polaroid02: "/images/story/editorial/polaroid-02/polaroid-02.jpg",
    },
    timeline: {
      milestone01: "/images/story/timeline/milestone-01/milestone-01.jpg",
      milestone02: "/images/story/timeline/milestone-02/milestone-02.jpg",
      milestone03: "/images/story/timeline/milestone-03/milestone-03.jpg",
      milestone04: "/images/story/timeline/milestone-04/milestone-04.jpg",
    },
  },
  events: {
    wedding: "/images/events/wedding/wedding.svg",
    church: "/images/events/church/church.svg",
    groomHouse: "/images/events/groom-house/groom-house.svg",
  },
  directions: {
    churchMap: "/images/directions/church/church-map.jpg",
    eventSpaceMap: "/images/directions/event-space/event-space-map.jpg",
    groomHouseMap: "/images/directions/groom-house/groom-house-map.jpg",
  },
};

export const weddingConfig: WeddingDataConfig = {
  couple: {
    groom: "NIKE",
    bride: "ANN",
    connector: "&",
    monogram: "N & A",
    monogramShort: "N/A",
  },
  date: {
    dayOfWeek: "SUNDAY",
    day: 15,
    month: "NOVEMBER",
    year: 2026,
    time: "3:00 PM IST",
    formatted: "SUNDAY, 15 NOVEMBER 2026",
    iso: "2026-11-15T15:00:00+05:30",
  },
  location: {
    city: "GURUVAYUR",
    state: "KERALA",
    country: "INDIA",
    venueName: "New Pond Eventscape",
    address: "Kandanassery Rd, Guruvayur, Keralam 680102",
    display: "GURUVAYUR · KERALA",
  },
  teaser: {
    badge: "PRIVATE INVITATION",
    subtitle: "YOU'RE INVITED",
    openButtonText: "TAP TO OPEN",
    scrollHint: "Tap the seal or button to open",
  },
  invitation: {
    inviteLine1: "TOGETHER WITH OUR FAMILIES",
    inviteLine2: "WE INVITE YOU TO THE WEDDING OF",
    presenceNote: [
      "YOUR PRESENCE",
      "WILL MAKE OUR DAY",
      "EVEN MORE SPECIAL",
    ],
    ctaButtonText: "ENTER OUR WEDDING →",
  },
  storyIntro: {
    badge: "OUR STORY",
    headline: ["TWO SOULS,", "A SHARED JOURNEY"],
    subheading: "Perhaps It Was Grace",
    fullStoryTitle: "Perhaps It Was Grace",
    quote: "Some people make your world brighter just by being in it.",
    quoteAuthor: "Nike & Ann",
    portraitImage: weddingImages.story.editorial.polaroid01,
    portraitAlt: "Nike and Ann together",
    portraitCaption: "Kochi, 2024",
    fullStory: [
      "Some stories begin with a chance encounter. Ours began with our families, a little faith, and a matrimonial site.",
      "In October 2025, Chavara (the matrimonial site) brought together a boy from Thrissur and a girl from Kannur. Though we grew up in different parts of Kerala, with our own customs, rhythms, and ways of doing things, we shared the same values. That familiarity made it easy for something meaningful to begin.",
      "What began as a simple introduction soon became a conversation we both looked forward to. We clicked almost instantly, finding comfort in our shared values, similar upbringings, and grounded Malayali Christian roots. And somewhere between her deep faith and my more relaxed approach, we found a balance that felt entirely natural.",
      "When we finally met in December, during those breezy days, the ease we had found in our conversations carried effortlessly into real life. We decided to date, spend more time together, and see where life would take us.",
      "Six months may seem short, but it was long enough to know that we wanted a lifetime. In April, with our families as witnesses, we got engaged — a promise to grow together, live together, and stand by each other through all that life brings.",
      "Looking back, it feels like something more than coincidence. Two people who may never have crossed paths on their own, brought together by the people who knew them best, and perhaps by a little grace from above.",
      "And now, here we are — ready to turn a beautiful beginning into a lifetime of togetherness."
    ],
    polaroids: {
      top: {
        image: weddingImages.story.editorial.polaroid01,
        caption: "First steps",
        alt: "Nike and Ann with the illuminated tree sculpture"
      },
      bottom: {
        image: weddingImages.story.editorial.polaroid02,
        caption: "Forever feels right",
        alt: "Nike and Ann in festive traditional wear surrounded by warm lights"
      }
    }
  },
  storyTimeline: {
    badge: "OUR TIMELINE",
    title: "OUR STORY",
    subtitle: "The chapters that brought our hearts to forever",
    milestones: [
      {
        id: "faith-oct-2025",
        year: "OCT 2025",
        dateTag: "OCTOBER 2025",
        title: "A Little Faith",
        subtitle: "When Chavara Connected Us",
        shortDescription: "Chavara brought together a boy from Thrissur and a girl from Kannur together.",
        description:
          "In October 2025, Chavara (the matrimonial site) brought together a boy from Thrissur and a girl from Kannur. Finding comfort in our shared values, similar upbringings, and grounded Malayali Christian roots, a meaningful conversation began.",
        location: "Thrissur & Kannur · Kerala",
        image: weddingImages.story.timeline.milestone01,
        imageAlt: "Nike and Ann smiling together",
        orientation: "portrait",
      },
      {
        id: "meet-dec-2025",
        year: "DEC 2025",
        dateTag: "DECEMBER 2025",
        title: "The First Meet",
        subtitle: "Conversations Turned Real",
        shortDescription: "Those breezy days turned conversations into something real.",
        description:
          "When we finally met in December, during those breezy days, the ease we had found in our conversations carried effortlessly into real life. We decided to date, spend more time together, and see where life would take us.",
        location: "Kerala",
        image: weddingImages.story.timeline.milestone02,
        imageAlt: "Nike and Ann together in traditional and contemporary attire",
        orientation: "portrait",
      },
      {
        id: "engagement-apr-2026",
        year: "APR 2026",
        dateTag: "APRIL 2026",
        title: "Our Engagement",
        subtitle: "A Promise to Grow Together",
        shortDescription: "With our families as witnesses, we said yes to forever.",
        description:
          "Six months may seem short, but it was long enough to know that we wanted a lifetime. In April, with our families as witnesses, we got engaged — a promise to grow together, live together, and stand by each other through all that life brings.",
        location: "Kerala",
        image: weddingImages.story.timeline.milestone03,
        imageAlt: "Hands intertwined with engagement rings",
        orientation: "portrait",
      },
      {
        id: "wedding-nov-2026",
        year: "NOV 2026",
        dateTag: "NOVEMBER 2026",
        title: "A Lifetime Ahead",
        subtitle: "Perhaps It Was Grace",
        shortDescription: "Two people, one journey, perhaps it was grace.",
        description:
          "Looking back, it feels like something more than coincidence. Two people brought together by the people who knew them best, and perhaps by a little grace from above. And now, here we are — ready for a lifetime of togetherness.",
        location: "Thrissur · Kerala",
        image: weddingImages.story.timeline.milestone04,
        imageAlt: "Nike and Ann walking forward into their lifetime together",
        orientation: "portrait",
      },
    ],
    closingQuote: {
      line1: "And so our greatest adventure begins...",
      line2: "Sunday, 15 November 2026 · Thrissur, Kerala",
    },
  },
  events: {
    badge: "THE CELEBRATION",
    title: "EVENT DETAILS",
    subtitle: "Join us in our sacred traditions and joyous moments",
    // Day programme displayed inside the Event Details glass panel
    programmeSchedule: [
      { time: "02:00 PM", label: "Groom's House" },
      { time: "03:00 PM", label: "St. Joseph's Church, Kaveed" },
      { time: "06:00 PM – 10:00 PM", label: "Reception · New Pond Eventscape" },
    ],
    closingNote: ["WE CAN'T WAIT", "TO CELEBRATE WITH YOU"],
    events: [
      {
        id: "wedding",
        type: "church",
        badge: "THE SACRED CEREMONY",
        title: "The Wedding Ceremony",
        subtitle: "Solemnization & Nuptial Blessing",
        date: "Sunday, 15 November 2026",
        time: "3:00 PM IST",
        venue: "St. Joseph's Church, Kaveed",
        address: "J28F+745, Kaveed - Thamarayoor Road, Kaveed, Keralam 680505",
        phone: "0487 250 7557",
        description:
          "With the blessings of our parents and surrounded by the warmth of family and friends, we will unite as one under God's grace.",
        image: weddingImages.events.church,
        imageAlt: "Ceremonial church and nuptial blessing",
        dressCode: "MEN: Suit Up · LADIES: Elegant Evening Wear",
        dressCodeDetails: {
          men: "Suit Up",
          ladies: "Elegant Evening Wear",
        },
        mapUrl: "https://maps.app.goo.gl/RfBfQvkBvkVc7Ahb8?g_st=iw",
      },
      {
        id: "reception",
        type: "reception",
        badge: "THE CELEBRATION",
        title: "The Wedding Reception",
        subtitle: "Dinner & Joyous Celebration",
        date: "Sunday, 15 November 2026",
        time: "06:00 PM – 10:00 PM",
        venue: "New Pond Eventscape",
        address: "Kandanassery Rd, Guruvayur, Keralam 680102",
        phone: "062355 77177",
        description:
          "Join us for an evening of music, celebration, and fellowship as we toast to a lifetime of love and togetherness.",
        image: weddingImages.events.wedding,
        imageAlt: "Evening celebration and banquet at New Pond Eventscape",
        dressCode: "MEN: Suit Up · LADIES: Elegant Evening Wear",
        dressCodeDetails: {
          men: "Suit Up",
          ladies: "Elegant Evening Wear",
        },
        mapUrl: "https://maps.app.goo.gl/xBtrb94kyKfe3rzd6",
      },
      {
        id: "grooms-house",
        type: "grooms-house",
        badge: "TRADITIONAL GATHERING",
        title: "The Groom's House",
        subtitle: "Family Gathering & Welcome",
        date: "Sunday, 15 November 2026",
        time: "02:00 PM",
        venue: "The Gladwin's House",
        address: "J288+25M, Perakam, Keralam 680505",
        description:
          "An auspicious pre-ceremony gathering with close family and dear friends at the residence before departing for the church.",
        image: weddingImages.events.groomHouse,
        imageAlt: "The Gladwin's House family gathering",
        dressCode: "MEN: Suit Up · LADIES: Elegant Evening Wear",
        dressCodeDetails: {
          men: "Suit Up",
          ladies: "Elegant Evening Wear",
        },
        mapUrl: "https://maps.app.goo.gl/qFGEFSNSgaVG1C6C6?g_st=iw",
      },
    ],
  },
  travel: {
    badge: "DIRECTIONS",
    title: "GETTING THERE",
    subtitle: "Essential directions, map links, and arrival notes for our celebration destinations",
    destinations: [
      {
        id: "church",
        type: "church",
        category: "CHURCH",
        title: "St. Joseph's Church, Kaveed",
        subtitle: "The Sacred Marriage Ceremony",
        address: "J28F+745, Kaveed - Thamarayoor Road, Kaveed, Keralam 680505",
        cityLabel: "KAVEED, GURUVAYUR",
        phone: "0487 250 7557",
        isConfirmed: true,
        mapUrl: "https://maps.app.goo.gl/RfBfQvkBvkVc7Ahb8?g_st=iw",
        directionsButtonText: "OPEN IN GOOGLE MAPS",
        mapPreviewImage: weddingImages.directions.churchMap,
      },
      {
        id: "event-space",
        type: "venue",
        category: "EVENT SPACE",
        title: "New Pond Eventscape",
        subtitle: "The Evening Celebration & Reception",
        address: "Kandanassery Rd, Guruvayur, Keralam 680102",
        cityLabel: "GURUVAYUR, KERALA",
        phone: "062355 77177",
        isConfirmed: true,
        mapUrl: "https://maps.app.goo.gl/xBtrb94kyKfe3rzd6",
        directionsButtonText: "OPEN IN GOOGLE MAPS",
        mapPreviewImage: weddingImages.directions.eventSpaceMap,
      },
      {
        id: "grooms-house",
        type: "residence",
        category: "GROOM'S HOUSE",
        title: "The Gladwin's House",
        subtitle: "The Traditional Gathering & Family Residence",
        address: "J288+25M, Perakam, Keralam 680505",
        cityLabel: "PERAKAM, KERALA",
        contacts: ["9495957777", "9159896134"],
        isConfirmed: true,
        mapUrl: "https://maps.app.goo.gl/qFGEFSNSgaVG1C6C6?g_st=iw",
        directionsButtonText: "OPEN IN GOOGLE MAPS",
        mapPreviewImage: weddingImages.directions.groomHouseMap,
      },
    ],
  },
  rsvp: {
    badge: "KINDLY",
    title: "RSVP",
    subtitle: "Your presence would mean the world to us.",
    deadlineNote: "Kindly respond on or before 15 October 2026",
    footerQuote: "Your response means the world to us.",
    nameLabel: "YOUR NAME",
    namePlaceholder: "Full Name",
    attendanceQuestion: "WILL YOU BE JOINING US?",
    attendanceOptions: [
      {
        value: "yes",
        label: "YES, I'LL BE THERE",
        description: "Joyfully accepting with pleasure",
      },
      {
        value: "no",
        label: "NO, I'M SORRY I CAN'T",
        description: "Regretfully declining from afar",
      },
    ],
    guestCountQuestion: "HOW MANY GUESTS WILL BE ATTENDING?",
    minGuests: 1,
    maxGuests: 10,
    accommodation: {
      question: "WILL YOU BE STAYING WITH US?",
      phoneLabel: "PHONE NUMBER",
      phonePlaceholder: "+91 / Country Code & Mobile Number",
      peopleStayingLabel: "NUMBER OF PEOPLE STAYING",
      minPeople: 1,
      maxPeople: 10,
      arrivalDateLabel: "ARRIVAL DATE",
      departureDateLabel: "DEPARTURE DATE",
      roomsRequiredLabel: "ROOMS REQUIRED",
      minRooms: 1,
      maxRooms: 5,
    },
    messageLabel: "LEAVE A NOTE FOR THE COUPLE",
    messagePlaceholder: "Share your blessings, prayers, or memories with Nike & Ann...",
    submitButtonText: "SEND RSVP →",
    submittingButtonText: "RECORDING YOUR RESPONSE...",
    confirmation: {
      badge: "RESPONSE RECEIVED",
      title: "THANK YOU",
      attendingMessage: "WE WELCOME YOU TO OUR WEDDING",
      declinedMessage:
        "You will be dearly missed, but your blessings and warm prayers will be held close in our hearts.",
      closingNote: "With love & gratitude,\nNike & Ann",
      editButtonText: "Edit Your Response",
    },
  },
  contact: {
    whatsapp: "https://wa.me/?text=Warmest%20wishes%20Nike%20%26%20Ann!",
    instagram: "https://instagram.com",
    email: "mailto:celebration@nikeannwedding.com",
  },
  images: weddingImages,
  audio: {
    src: "/audio/background-music.mp3",
    title: "Nike & Ann Wedding Music",
    autoplayOnInteraction: true,
    defaultVolume: 0.45,
    loop: true,
  },
};


